# Generated by Django 5.1.4 on 2026-09-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('account_class', models.PositiveSmallIntegerField(help_text='Classe comptable 1–7')),
                ('category', models.CharField(max_length=80)),
                ('balance', models.BigIntegerField(default=0, help_text='Solde en BIF')),
            ],
            options={
                'verbose_name': 'Compte comptable',
                'verbose_name_plural': 'Comptes comptables',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=40, unique=True)),
                ('date', models.DateField()),
                ('document_ref', models.CharField(blank=True, max_length=80)),
                ('label', models.CharField(max_length=255)),
                ('total_debit', models.BigIntegerField(default=0)),
                ('total_credit', models.BigIntegerField(default=0)),
                ('is_balanced', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('EXTOURNE', 'Extourné')], default='BROUILLON', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'verbose_name_plural': 'Écritures comptables',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountingEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.BigIntegerField(default=0)),
                ('credit', models.BigIntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': "Ligne d'écriture",
                'verbose_name_plural': "Lignes d'écriture",
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('budget', models.BigIntegerField(default=0, help_text='Budget annuel en BIF')),
                ('spent', models.BigIntegerField(default=0, help_text='Dépensé en BIF')),
            ],
            options={
                'verbose_name': 'Centre de coût',
                'verbose_name_plural': 'Centres de coût',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DisbursementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=40, unique=True)),
                ('amount', models.BigIntegerField(help_text='Montant demandé en BIF')),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('Brouillon', 'Brouillon'), ('Validé', 'Validé'), ('Confirmé', 'Confirmé'), ('Approuvé', 'Approuvé'), ('Écriture Générée', 'Écriture Générée'), ('Rejeté', 'Rejeté')], default='Brouillon', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demande de décaissement',
                'verbose_name_plural': 'Demandes de décaissement',
                'ordering': ['-created_at'],
            },
        ),
    ]
