# Generated by Django 5.1.4 on 2026-09-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unpaid_months_count', models.PositiveSmallIntegerField(default=0)),
                ('base_rent_total', models.BigIntegerField(default=0)),
                ('penalties_total', models.BigIntegerField(default=0)),
                ('total_due', models.BigIntegerField(default=0)),
                ('last_reminder_date', models.DateField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Élevé'), ('CRITIQUE', 'Critique')], default='FAIBLE', max_length=10)),
                ('status', models.CharField(choices=[('Dossier Ouvert', 'Dossier Ouvert'), ('Relance J-5', 'Relance J-5'), ('Mise en demeure', 'Mise en demeure'), ('Procédure Scellé', 'Procédure Scellé'), ('Régularisé', 'Régularisé')], default='Dossier Ouvert', max_length=25)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contentieux',
                'verbose_name_plural': 'Contentieux',
                'ordering': ['-total_due'],
            },
        ),
        migrations.CreateModel(
            name='ReminderHistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Rappel J-5', 'Rappel J-5'), ('Retard fin de mois', 'Retard fin de mois'), ('Mise en demeure', 'Mise en demeure'), ('Manuel', 'Manuel')], max_length=25)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email')], max_length=5)),
                ('destination', models.CharField(help_text='Numéro ou adresse e-mail', max_length=100)),
                ('status', models.CharField(choices=[('Envoyé', 'Envoyé'), ('Échec', 'Échec')], default='Envoyé', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Historique relance',
                'verbose_name_plural': 'Historiques relances',
                'ordering': ['-sent_at'],
            },
        ),
    ]
