# Generated by Django 5.1.4 on 2026-09-01 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('disputes', '0001_initial'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='core.place'),
        ),
        migrations.AddField(
            model_name='reminderhistoryitem',
            name='dispute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='disputes.dispute'),
        ),
    ]
