# Generated by Django 5.1.4 on 2026-09-01 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('identity_card_number', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='merchants/')),
                ('status', models.CharField(choices=[('ACTIF', 'Actif'), ('EN_LITIGE', 'En litige'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=10)),
                ('amount_due', models.BigIntegerField(default=0, help_text='Arriérés totaux en BIF')),
                ('registered_at', models.DateField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Commerçant',
                'verbose_name_plural': 'Commerçants',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rent', models.BigIntegerField(help_text='Loyer mensuel en BIF')),
                ('deposit_months', models.PositiveSmallIntegerField(default=2)),
                ('deposit_amount', models.BigIntegerField(help_text='Caution = deposit_months × monthly_rent')),
                ('periodicity', models.CharField(choices=[('Mensuel', 'Mensuel'), ('Trimestriel', 'Trimestriel'), ('Annuel', 'Annuel')], default='Mensuel', max_length=15)),
                ('status', models.CharField(choices=[('ACTIF', 'Actif'), ('RESILIE', 'Résilié'), ('EN_LITIGE', 'En litige')], default='ACTIF', max_length=10)),
                ('sublease_allowed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.place')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-created_at'],
            },
        ),
    ]
