# Generated by Django 5.1.4 on 2026-09-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DueDateInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=40, unique=True)),
                ('period', models.CharField(help_text='Ex: Août 2026', max_length=30)),
                ('due_date', models.DateField()),
                ('amount', models.BigIntegerField(help_text='Montant de base en BIF')),
                ('paid_amount', models.BigIntegerField(default=0)),
                ('remaining_amount', models.BigIntegerField()),
                ('status', models.CharField(choices=[('A_VENIR', 'À venir'), ('PAYEE', 'Payée'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée'), ('IMPAYEE', 'Impayée'), ('EN_RETARD', 'En retard')], default='A_VENIR', max_length=25)),
                ('penalty_amount', models.BigIntegerField(default=0, help_text='Pénalité 5% si en retard')),
                ('days_overdue', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Échéance / Facture',
                'verbose_name_plural': 'Échéances / Factures',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.BigIntegerField()),
                ('method', models.CharField(choices=[('Virement', 'Virement bancaire'), ('Mobile Money', 'Mobile Money'), ('Espèces', 'Espèces')], max_length=15)),
                ('reference', models.CharField(help_text='Numéro de transaction / reçu', max_length=80)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=15)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_number', models.CharField(max_length=40, unique=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('declared_amount', models.BigIntegerField()),
                ('expected_amount', models.BigIntegerField()),
                ('method', models.CharField(choices=[('Virement', 'Virement bancaire'), ('Mobile Money', 'Mobile Money'), ('Espèces', 'Espèces')], max_length=15)),
                ('file', models.FileField(upload_to='payment_slips/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=15)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Bordereau de paiement',
                'verbose_name_plural': 'Bordereaux de paiement',
                'ordering': ['-submission_date'],
            },
        ),
    ]
