# Generated by Django 5.1.4 on 2026-09-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mall Kamenge', max_length=100)),
                ('city', models.CharField(default='Bujumbura, Burundi', max_length=100)),
                ('currency', models.CharField(default='BIF', max_length=10)),
                ('penalty_rate_percent', models.DecimalField(decimal_places=2, default=5.0, help_text='Taux de pénalité de retard (%)', max_digits=5)),
                ('billing_day_of_month', models.PositiveSmallIntegerField(default=1, help_text='Jour de génération des échéances (1–28)')),
                ('grace_period_days', models.PositiveSmallIntegerField(default=5, help_text='Nombre de jours de grâce avant pénalité')),
                ('decimal_precision', models.PositiveSmallIntegerField(default=0)),
                ('sms_notifications_enabled', models.BooleanField(default=True)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres du marché',
                'verbose_name_plural': 'Paramètres du marché',
            },
        ),
    ]
