# Generated by Django 5.1.4 on 2026-09-02 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(default=list)),
                ('is_system_role', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Rôle du personnel',
                'verbose_name_plural': 'Rôles du personnel',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_area',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.staffrole'),
        ),
    ]
