# Generated by Django 5.1.4 on 2026-09-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, help_text='Snapshot at time of action', max_length=150)),
                ('user_role', models.CharField(blank=True, choices=[('ADMIN', 'Administrateur'), ('AGENT', 'Agent du marché'), ('MERCHANT', 'Commerçant')], max_length=10)),
                ('action', models.CharField(max_length=255)),
                ('resource', models.CharField(max_length=255)),
                ('old_status', models.CharField(blank=True, max_length=100)),
                ('new_status', models.CharField(blank=True, max_length=100)),
                ('details', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('ALERTE', 'Alerte'), ('CRITIQUE', 'Critique')], default='INFO', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-timestamp'],
            },
        ),
    ]
