# Generated by Django 5.1.4 on 2026-09-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('type', models.CharField(choices=[('Boutique', 'Boutique'), ('Kiosque', 'Kiosque'), ('Stand', 'Stand')], max_length=10)),
                ('surface_m2', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monthly_rent', models.BigIntegerField(help_text='Loyer mensuel en BIF')),
                ('status', models.CharField(choices=[('LIBRE', 'Libre'), ('OCCUPE', 'Occupé'), ('PREUVE_EN_ATTENTE', 'Preuve en attente'), ('IMPAYE', 'Impayé'), ('MAINTENANCE', 'Maintenance'), ('SCELLE', 'Scellé')], default='LIBRE', max_length=20)),
                ('last_due_date', models.DateField(blank=True, null=True)),
                ('total_due', models.BigIntegerField(default=0, help_text='Arriérés cumulés en BIF')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Emplacement',
                'verbose_name_plural': 'Emplacements',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('total_places', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['code'],
            },
        ),
    ]
