# Generated by Django 5.1.4 on 2026-09-01 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='current_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='merchants.contract'),
        ),
        migrations.AddField(
            model_name='place',
            name='current_merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupied_places', to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='place',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='core.zone'),
        ),
    ]
